### ISSUE TITLE
ML web apps 

### ISSUE THREAD

**Issue by randallscott25** [amrrs/youtube-r-snippets#2]
![image](https://user-images.githubusercontent.com/54422413/92489023-48294a80-f1bd-11ea-988d-b80dfd8af984.png)
per your request from my question on youtube

**Comment by amrrs** [comment]
Hey @randallscott25 did you try to restart your colab runtime and see if it fixes ?

**Comment by randallscott25** [comment]
I am doing that now. It will take sometime. it as at the end on my ipynb. I am trying to create a dashboard for my masters final.

**Comment by randallscott25** [comment]
it is my first time to create a dashboard, so I most likely don't know what I am doing. 
I have a massive colab ipynb containing several plotly maps and graphs, kmeans and linear regression. at the end of the notebook I was going to invoke your code essentially to 'start the creation of the dashboard', I was then going to host it via ngrok or try to upload to like heroku(sp) 

okay its back up and it looks like it is working. woohoo, a starting point.
![image](https://user-images.githubusercontent.com/54422413/92491178-efa77c80-f1bf-11ea-9a90-2ce09cd9cc9d.png)

Thanks Amrrs!

**Comment by randallscott25** [comment]
Stellar person. Thank you for the help

**Comment by amrrs** [comment]
Congratulations @randallscott25 🎉 Hope your final's project makes an awesome impression!
